#!/usr/bin/env python3
"""Migrate catalog.json to v2 schema: multi-domain, jurisdiction, provenance, by_domain index."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CATALOG_PATH = REPO / "legal_corpus" / "acts" / "catalog.json"

# Domain remapping for existing acts
DOMAIN_FIXES = {
    "BSA": {
        "domain": "evidence",
        "domains": ["evidence", "criminal_law"],
    },
    "EPA1986": {
        "domain": "environment",
        "domains": ["environment", "general_legal"],
    },
    "LSA1987": {
        "domain": "social_welfare",
        "domains": ["social_welfare", "general_legal"],
    },
    "PHRA1993": {
        "domain": "human_rights",
        "domains": ["human_rights", "constitutional_law"],
    },
}

# New acts to append (Stage 1 + pilot additions not in original catalog)
NEW_ACTS = [
    {
        "act_id": "CPC1908",
        "official_title": "The Code of Civil Procedure, 1908",
        "short_title": "CPC, 1908",
        "year": 1908,
        "act_number": "5 of 1908",
        "category": "Civil Procedure",
        "domain": "civil_procedure",
        "domains": ["civil_procedure", "civil_law"],
        "sub_domains": ["plaint", "injunction", "execution", "appeals"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Legislative Department / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2191",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1909-01-01",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["cpc", "cpc 1908", "code of civil procedure", "code of civil procedure 1908"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "SOGA1930",
        "official_title": "The Sale of Goods Act, 1930",
        "short_title": "Sale of Goods Act, 1930",
        "year": 1930,
        "act_number": "3 of 1930",
        "category": "Commercial / Contract",
        "domain": "commercial_law",
        "domains": ["commercial_law", "contract"],
        "sub_domains": ["sale", "warranty", "delivery", "acceptance"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2325",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1930-07-01",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["sale of goods act", "soga", "sale of goods act 1930"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "IPA1932",
        "official_title": "The Indian Partnership Act, 1932",
        "short_title": "Partnership Act, 1932",
        "year": 1932,
        "act_number": "9 of 1932",
        "category": "Commercial",
        "domain": "commercial_law",
        "domains": ["commercial_law", "contract"],
        "sub_domains": ["partnership", "firm", "dissolution"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2328",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1932-10-01",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["partnership act", "indian partnership act", "partnership act 1932"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "IEA1882",
        "official_title": "The Indian Easements Act, 1882",
        "short_title": "Easements Act, 1882",
        "year": 1882,
        "act_number": "5 of 1882",
        "category": "Property",
        "domain": "property",
        "domains": ["property", "civil_law"],
        "sub_domains": ["easements", "prescriptive_rights"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Legislative Department / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2339",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1882-07-01",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["easements act", "indian easements act", "easements act 1882"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "ITA1882",
        "official_title": "The Indian Trusts Act, 1882",
        "short_title": "Trusts Act, 1882",
        "year": 1882,
        "act_number": "2 of 1882",
        "category": "Property / Civil",
        "domain": "property",
        "domains": ["property", "civil_law"],
        "sub_domains": ["trusts", "trustees", "beneficiaries"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Legislative Department / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2336",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1882-03-01",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["trusts act", "indian trusts act", "trusts act 1882"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "LLP2008",
        "official_title": "The Limited Liability Partnership Act, 2008",
        "short_title": "LLP Act, 2008",
        "year": 2008,
        "act_number": "6 of 2009",
        "category": "Corporate / Commercial",
        "domain": "company_commercial_law",
        "domains": ["company_commercial_law", "commercial_law"],
        "sub_domains": ["llp", "partners", "incorporation"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Corporate Affairs",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2070",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2009-03-31",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["llp act", "limited liability partnership act", "llp act 2008"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "COMPETITION2002",
        "official_title": "The Competition Act, 2002",
        "short_title": "Competition Act, 2002",
        "year": 2002,
        "act_number": "12 of 2003",
        "category": "Commercial / Regulatory",
        "domain": "commercial_law",
        "domains": ["commercial_law", "general_legal"],
        "sub_domains": ["anti_competitive", "combinations", "cci"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Corporate Affairs",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2033",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2003-01-31",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["competition act", "competition act 2002", "cci act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "COMMERCIALCOURTS2015",
        "official_title": "The Commercial Courts Act, 2015",
        "short_title": "Commercial Courts Act, 2015",
        "year": 2015,
        "act_number": "4 of 2016",
        "category": "Commercial / Civil Procedure",
        "domain": "commercial_law",
        "domains": ["commercial_law", "civil_procedure"],
        "sub_domains": ["commercial_disputes", "pre_institution_mediation"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2149",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2016-01-15",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["commercial courts act", "commercial courts act 2015"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "HMA1955",
        "official_title": "The Hindu Marriage Act, 1955",
        "short_title": "HMA, 1955",
        "year": 1955,
        "act_number": "25 of 1955",
        "category": "Family / Personal Law",
        "domain": "family_law",
        "domains": ["family_law", "personal_law"],
        "personal_law_framework": "hindu",
        "sub_domains": ["marriage", "divorce", "restitution", "judicial_separation"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1560",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1955-05-18",
        "priority": "tier_1",
        "ingestion_stage": "pilot",
        "aliases": ["hma", "hindu marriage act", "hindu marriage act 1955"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "HSA1956",
        "official_title": "The Hindu Succession Act, 1956",
        "short_title": "HSA, 1956",
        "year": 1956,
        "act_number": "30 of 1956",
        "category": "Family / Personal Law",
        "domain": "family_law",
        "domains": ["family_law", "personal_law", "property"],
        "personal_law_framework": "hindu",
        "sub_domains": ["succession", "inheritance", "coparcenary"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1561",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1956-06-17",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["hsa", "hindu succession act", "hindu succession act 1956"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "HAMA1956",
        "official_title": "The Hindu Adoptions and Maintenance Act, 1956",
        "short_title": "HAMA, 1956",
        "year": 1956,
        "act_number": "78 of 1956",
        "category": "Family / Personal Law",
        "domain": "family_law",
        "domains": ["family_law", "personal_law"],
        "personal_law_framework": "hindu",
        "sub_domains": ["adoption", "maintenance"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1562",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1956-12-21",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["hama", "hindu adoptions and maintenance act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "HMGA1956",
        "official_title": "The Hindu Minority and Guardianship Act, 1956",
        "short_title": "HMGA, 1956",
        "year": 1956,
        "act_number": "32 of 1956",
        "category": "Family / Personal Law",
        "domain": "family_law",
        "domains": ["family_law", "personal_law"],
        "personal_law_framework": "hindu",
        "sub_domains": ["guardianship", "minor"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1563",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1956-08-25",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["hmga", "hindu minority and guardianship act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "SMA1954",
        "official_title": "The Special Marriage Act, 1954",
        "short_title": "SMA, 1954",
        "year": 1954,
        "act_number": "43 of 1954",
        "category": "Family / Personal Law",
        "domain": "family_law",
        "domains": ["family_law", "personal_law"],
        "personal_law_framework": "special_marriage",
        "sub_domains": ["civil_marriage", "interfaith", "registration"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1559",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1955-01-01",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["sma", "special marriage act", "special marriage act 1954"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "GWA1890",
        "official_title": "The Guardians and Wards Act, 1890",
        "short_title": "GWA, 1890",
        "year": 1890,
        "act_number": "8 of 1890",
        "category": "Family",
        "domain": "family_law",
        "domains": ["family_law", "personal_law"],
        "personal_law_framework": "secular_family",
        "sub_domains": ["guardianship", "wards"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Legislative Department / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2305",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1890-03-21",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["gwa", "guardians and wards act", "guardians and wards act 1890"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "FCA1984",
        "official_title": "The Family Courts Act, 1984",
        "short_title": "Family Courts Act, 1984",
        "year": 1984,
        "act_number": "66 of 1984",
        "category": "Family / Courts",
        "domain": "family_law",
        "domains": ["family_law", "civil_procedure"],
        "personal_law_framework": "secular_family",
        "sub_domains": ["family_courts", "conciliation"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1886",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1984-09-14",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["family courts act", "family courts act 1984"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "MWPSC2007",
        "official_title": "The Maintenance and Welfare of Parents and Senior Citizens Act, 2007",
        "short_title": "Senior Citizens Act, 2007",
        "year": 2007,
        "act_number": "56 of 2007",
        "category": "Family / Social Welfare",
        "domain": "family_law",
        "domains": ["family_law", "social_welfare"],
        "personal_law_framework": "secular_family",
        "sub_domains": ["maintenance", "senior_citizens"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Social Justice and Empowerment",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2068",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2007-12-31",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["senior citizens act", "maintenance and welfare of parents and senior citizens act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "PCMA2006",
        "official_title": "The Prohibition of Child Marriage Act, 2006",
        "short_title": "PCMA, 2006",
        "year": 2006,
        "act_number": "6 of 2007",
        "category": "Family / Child Protection",
        "domain": "family_law",
        "domains": ["family_law", "social_welfare"],
        "personal_law_framework": "secular_family",
        "sub_domains": ["child_marriage"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Women and Child Development",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2066",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2007-01-10",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["pcma", "prohibition of child marriage act", "child marriage act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "MWPR2019",
        "official_title": "The Muslim Women (Protection of Rights on Marriage) Act, 2019",
        "short_title": "Triple Talaq Act, 2019",
        "year": 2019,
        "act_number": "20 of 2019",
        "category": "Family / Personal Law",
        "domain": "personal_law",
        "domains": ["personal_law", "family_law"],
        "personal_law_framework": "muslim_statutes",
        "sub_domains": ["talaq", "marriage"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Law and Justice",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/15255",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2019-09-19",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["triple talaq act", "muslim women protection of rights on marriage act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "ITA2025",
        "official_title": "The Income-tax Act, 2025",
        "short_title": "Income-tax Act, 2025",
        "year": 2025,
        "act_number": "30 of 2025",
        "category": "Tax / Direct Tax",
        "domain": "tax",
        "domains": ["tax"],
        "sub_domains": ["income_tax", "assessment", "deductions"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Central Board of Direct Taxes",
        "official_url": "https://www.incometaxindia.gov.in/documents/d/guest/income_tax_act_2025_as_amended_by_fa_act_2026-pdf",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2026-04-01",
        "repeals": ["Income-tax Act, 1961"],
        "priority": "tier_1",
        "ingestion_stage": "pilot",
        "aliases": ["income tax act 2025", "ita 2025", "income-tax act 2025"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "ITA1961",
        "official_title": "The Income-tax Act, 1961",
        "short_title": "Income-tax Act, 1961",
        "year": 1961,
        "act_number": "43 of 1961",
        "category": "Tax / Direct Tax (Historical)",
        "domain": "tax",
        "domains": ["tax"],
        "sub_domains": ["income_tax", "assessment", "historical"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Central Board of Direct Taxes",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1578",
        "source_type": "official_gazette",
        "status": "repealed",
        "effective_from": "1962-04-01",
        "effective_to": "2026-03-31",
        "assessment_year_to": "2025-26",
        "implementation_notes": "Governs tax years beginning before 1 April 2026; do not present as current law",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["income tax act 1961", "ita 1961", "income-tax act 1961"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "CGST2017",
        "official_title": "The Central Goods and Services Tax Act, 2017",
        "short_title": "CGST Act, 2017",
        "year": 2017,
        "act_number": "12 of 2017",
        "category": "Tax / GST",
        "domain": "gst",
        "domains": ["gst", "tax"],
        "gst_component": "CGST",
        "sub_domains": ["input_tax_credit", "registration", "returns"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Central Board of Indirect Taxes and Customs",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2167",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2017-07-01",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["cgst", "cgst act", "central goods and services tax act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "IGST2017",
        "official_title": "The Integrated Goods and Services Tax Act, 2017",
        "short_title": "IGST Act, 2017",
        "year": 2017,
        "act_number": "13 of 2017",
        "category": "Tax / GST",
        "domain": "gst",
        "domains": ["gst", "tax"],
        "gst_component": "IGST",
        "sub_domains": ["inter_state_supply", "imports"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Central Board of Indirect Taxes and Customs",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2168",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2017-07-01",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["igst", "igst act", "integrated goods and services tax act"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "CUSTOMS1962",
        "official_title": "The Customs Act, 1962",
        "short_title": "Customs Act, 1962",
        "year": 1962,
        "act_number": "52 of 1962",
        "category": "Tax / Indirect Tax",
        "domain": "tax",
        "domains": ["tax"],
        "sub_domains": ["customs", "imports", "exports"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Central Board of Indirect Taxes and Customs",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1577",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1962-12-13",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["customs act", "customs act 1962"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "WATER1974",
        "official_title": "The Water (Prevention and Control of Pollution) Act, 1974",
        "short_title": "Water Act, 1974",
        "year": 1974,
        "act_number": "6 of 1974",
        "category": "Environmental",
        "domain": "environment",
        "domains": ["environment"],
        "sub_domains": ["water_pollution", "spcb"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1388",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1974-03-23",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["water act", "water pollution act", "water act 1974"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "AIR1981",
        "official_title": "The Air (Prevention and Control of Pollution) Act, 1981",
        "short_title": "Air Act, 1981",
        "year": 1981,
        "act_number": "14 of 1981",
        "category": "Environmental",
        "domain": "environment",
        "domains": ["environment"],
        "sub_domains": ["air_pollution", "spcb"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1868",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1981-03-29",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["air act", "air pollution act", "air act 1981"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "WPA1972",
        "official_title": "The Wild Life (Protection) Act, 1972",
        "short_title": "Wildlife Act, 1972",
        "year": 1972,
        "act_number": "53 of 1972",
        "category": "Environmental",
        "domain": "environment",
        "domains": ["environment"],
        "sub_domains": ["wildlife", "sanctuaries", "national_parks"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1393",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1972-09-09",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["wildlife act", "wild life protection act", "wildlife act 1972"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "NGT2010",
        "official_title": "The National Green Tribunal Act, 2010",
        "short_title": "NGT Act, 2010",
        "year": 2010,
        "act_number": "19 of 2010",
        "category": "Environmental / Tribunals",
        "domain": "environment",
        "domains": ["environment", "civil_procedure"],
        "sub_domains": ["ngt", "environmental_disputes"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2095",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2010-10-18",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["ngt act", "national green tribunal act", "ngt act 2010"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "BDA2002",
        "official_title": "The Biological Diversity Act, 2002",
        "short_title": "Biodiversity Act, 2002",
        "year": 2002,
        "act_number": "18 of 2003",
        "category": "Environmental",
        "domain": "environment",
        "domains": ["environment"],
        "sub_domains": ["biodiversity", "access_benefit_sharing"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2037",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2003-10-05",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["biodiversity act", "biological diversity act", "bda 2002"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "FCA1980",
        "official_title": "The Forest (Conservation) Act, 1980",
        "short_title": "Forest Conservation Act, 1980",
        "year": 1980,
        "act_number": "69 of 1980",
        "category": "Environmental / Forest",
        "domain": "environment",
        "domains": ["environment"],
        "sub_domains": ["forest", "diversion"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Environment, Forest and Climate Change",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1867",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "1980-10-25",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["forest conservation act", "fca 1980", "forest act 1980"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "COW2019",
        "official_title": "The Code on Wages, 2019",
        "short_title": "Code on Wages, 2019",
        "year": 2019,
        "act_number": "29 of 2019",
        "category": "Labour",
        "domain": "labour_employment",
        "domains": ["labour_employment"],
        "sub_domains": ["wages", "minimum_wages", "payment_of_wages"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Labour and Employment",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/15254",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2025-11-21",
        "implementation_notes": "Central Rules notified 8 May 2026; state rules vary",
        "repeals": ["Minimum Wages Act, 1948", "Payment of Wages Act, 1936", "Payment of Bonus Act, 1965", "Equal Remuneration Act, 1976"],
        "priority": "tier_1",
        "ingestion_stage": "pilot",
        "aliases": ["code on wages", "code on wages 2019", "wages code"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "IRC2020",
        "official_title": "The Industrial Relations Code, 2020",
        "short_title": "Industrial Relations Code, 2020",
        "year": 2020,
        "act_number": "35 of 2020",
        "category": "Labour",
        "domain": "labour_employment",
        "domains": ["labour_employment"],
        "sub_domains": ["industrial_disputes", "trade_unions", "standing_orders"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Labour and Employment",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/15257",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2025-11-21",
        "implementation_notes": "Central Rules notified 8 May 2026; state rules vary",
        "repeals": ["Industrial Disputes Act, 1947", "Trade Unions Act, 1926", "Industrial Employment (Standing Orders) Act, 1946"],
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["industrial relations code", "irc 2020", "industrial relations code 2020"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "CSS2020",
        "official_title": "The Code on Social Security, 2020",
        "short_title": "Code on Social Security, 2020",
        "year": 2020,
        "act_number": "36 of 2020",
        "category": "Labour",
        "domain": "labour_employment",
        "domains": ["labour_employment"],
        "sub_domains": ["epf", "esi", "gratuity", "maternity", "gig_workers"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Labour and Employment",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/15258",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2025-11-21",
        "implementation_notes": "Central Rules notified 8 May 2026; state rules vary",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["code on social security", "social security code 2020"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "OSH2020",
        "official_title": "The Occupational Safety, Health and Working Conditions Code, 2020",
        "short_title": "OSH Code, 2020",
        "year": 2020,
        "act_number": "37 of 2020",
        "category": "Labour",
        "domain": "labour_employment",
        "domains": ["labour_employment"],
        "sub_domains": ["factories", "mines", "contract_labour", "occupational_safety"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Labour and Employment",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/15259",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2025-11-21",
        "implementation_notes": "Central Rules notified 8 May 2026; state rules vary",
        "priority": "tier_1",
        "ingestion_stage": "stage_1",
        "aliases": ["osh code", "occupational safety code", "osh code 2020"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "DESIGNS2000",
        "official_title": "The Designs Act, 2000",
        "short_title": "Designs Act, 2000",
        "year": 2000,
        "act_number": "16 of 2000",
        "category": "Intellectual Property",
        "domain": "intellectual_property",
        "domains": ["intellectual_property"],
        "sub_domains": ["designs", "registration", "infringement"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / DPIIT",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1998",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2000-05-11",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["designs act", "designs act 2000"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "GI1999",
        "official_title": "The Geographical Indications of Goods (Registration and Protection) Act, 1999",
        "short_title": "GI Act, 1999",
        "year": 1999,
        "act_number": "48 of 1999",
        "category": "Intellectual Property",
        "domain": "intellectual_property",
        "domains": ["intellectual_property"],
        "sub_domains": ["geographical_indications", "registration"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / DPIIT",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/1994",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2003-09-15",
        "priority": "tier_2",
        "ingestion_stage": "stage_1",
        "aliases": ["gi act", "geographical indications act", "gi act 1999"],
        "ingestion_status": "pending_source",
    },
    {
        "act_id": "PPVFR2001",
        "official_title": "The Protection of Plant Varieties and Farmers' Rights Act, 2001",
        "short_title": "PPVFR Act, 2001",
        "year": 2001,
        "act_number": "53 of 2001",
        "category": "Intellectual Property / Agriculture",
        "domain": "intellectual_property",
        "domains": ["intellectual_property"],
        "sub_domains": ["plant_varieties", "farmers_rights"],
        "jurisdiction_level": "CENTRAL",
        "jurisdiction": "India",
        "document_type": "STATUTE",
        "source_authority": "Parliament of India / Ministry of Agriculture",
        "official_url": "https://www.indiacode.gov.in/handle/123456789/2040",
        "source_type": "official_gazette",
        "status": "in_force",
        "effective_from": "2001-10-30",
        "priority": "tier_3",
        "ingestion_stage": "stage_1",
        "aliases": ["ppvfr act", "plant varieties act", "protection of plant varieties act"],
        "ingestion_status": "pending_source",
    },
]

STAGE_MAP = {
    "BNS2023": "ingested",
    "BNSS2023": "ingested",
    "BSA": "ingested",
    "ICA1872": "pilot",
    "COMPANIES2013": "pilot",
    "ITA2025": "pilot",
    "EPA1986": "pilot",
    "COW2019": "pilot",
    "COPYRIGHT1957": "pilot",
    "HMA1955": "pilot",
}


def normalize_act(act: dict) -> dict:
    act_id = act["act_id"]
    if act_id in DOMAIN_FIXES:
        act.update(DOMAIN_FIXES[act_id])

    if "domains" not in act:
        act["domains"] = [act.get("domain", "general_legal")]

    act.setdefault("jurisdiction_level", "CENTRAL")
    act.setdefault("source_type", "official_gazette")
    act.setdefault("state", None)

    doc_type = str(act.get("document_type", "statute")).upper()
    if doc_type == "STATUTE" or doc_type == "statute":
        act["document_type"] = "STATUTE"
    else:
        act["document_type"] = doc_type

    if act_id in STAGE_MAP and "ingestion_stage" not in act:
        act["ingestion_stage"] = STAGE_MAP[act_id]
    elif "ingestion_stage" not in act:
        if act.get("ingestion_status") == "ingested":
            act["ingestion_stage"] = "ingested"
        elif act.get("priority") == "tier_1":
            act["ingestion_stage"] = "stage_1"
        else:
            act["ingestion_stage"] = "stage_1"

    if act.get("ingestion_status") == "ingested" and not act.get("source_file"):
        pass  # keep existing source_file

    return act


def build_by_domain(acts: list[dict]) -> dict[str, list[str]]:
    index: dict[str, list[str]] = defaultdict(list)
    for act in acts:
        for domain in act.get("domains", [act.get("domain", "general_legal")]):
            index[domain].append(act["act_id"])
    return dict(sorted(index.items()))


def main() -> int:
    data = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    existing_ids = {a["act_id"] for a in data.get("acts", [])}
    acts = [normalize_act(dict(a)) for a in data.get("acts", [])]
    for new_act in NEW_ACTS:
        if new_act["act_id"] not in existing_ids:
            acts.append(normalize_act(dict(new_act)))
            existing_ids.add(new_act["act_id"])

    out = {
        "version": "2.0",
        "last_updated": date.today().isoformat(),
        "jurisdiction": "India",
        "authority_default": data.get(
            "authority_default",
            "Parliament of India / Legislative Department, Ministry of Law and Justice",
        ),
        "taxonomy_path": "legal_corpus/taxonomy/domains.json",
        "by_domain": build_by_domain(acts),
        "acts": acts,
    }
    CATALOG_PATH.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Enhanced catalog: {len(acts)} acts, {len(out['by_domain'])} domain buckets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
