import { DISPUTE_OPTIONS, INDIA_REGIONS, PARTY_TYPE_OPTIONS } from "./constants";
import type { FieldSpec, TemplateSpec } from "./types";

const REGION_OPTIONS = INDIA_REGIONS.map((region) => ({ value: region, label: region }));

function field(
  id: string,
  label: string,
  placeholderLabel: string,
  type: FieldSpec["type"],
  requirement: FieldSpec["requirement"],
  step: string,
  extra: Partial<FieldSpec> = {},
): FieldSpec {
  return { id, label, placeholderLabel, type, requirement, step, ...extra };
}

function jurisdictionFields(step = "jurisdiction"): FieldSpec[] {
  return [
    field("jurisdiction_country", "Jurisdiction", "JURISDICTION", "select", "required", step, {
      help: "The generated draft retains this jurisdiction. Laws vary by place.",
      options: [{ value: "IN", label: "India" }],
    }),
    field("jurisdiction_region", "State / Union Territory", "STATE OR UNION TERRITORY", "select", "required", step, {
      help: "Required because contract and property rules can vary within India.",
      options: REGION_OPTIONS,
    }),
    field("governing_law_seat", "Seat / place for disputes", "DISPUTE SEAT", "text", "recommended", step, {
      help: "City or district where disputes are to be heard, if the parties have agreed one.",
    }),
  ];
}

export const RENTAL_AGREEMENT_TAMIL_NADU_TEMPLATE: TemplateSpec = {
  id: "rental_agreement_tamil_nadu",
  category: "agreement",
  title: "Tamil Nadu Rental Agreement (வாடகை ஒப்பந்த பத்திரம்)",
  description: "Official 11-month residential tenancy agreement in Tamil Nadu with schedule of property and dual witness attestation.",
  documentType: "Residential Rental Agreement (Tamil Nadu)",
  jurisdictionCountry: "IN",
  jurisdictionRegion: "Tamil Nadu",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "Tamil Nadu Registration Department & TNRRRLT Act Rules",
    document_name: "Model Tenancy Agreement under Tamil Nadu Regulation of Rights and Responsibilities of Landlords and Tenants Act",
    reference_date: "2026-01-01",
  },
  applicability: "Residential leases and 11-month tenancies across Tamil Nadu (Chennai, Coimbatore, Madurai, Salem, etc.)",
  executionRequirements: [
    "To be executed on non-judicial stamp paper of prescribed value under TN Stamp Act",
    "Signed by Landlord and Tenant on each page",
    "Attested by two witnesses with full names, parentage, and addresses",
    "Registration on TN Tenancy portal (tenancy.tn.gov.in) within 90 days",
  ],
  parties: [
    { id: "landlord", role: "Landlord / Lessor", nameField: "landlord_name", typeField: "landlord_type", addressField: "landlord_address" },
    { id: "tenant", role: "Tenant / Lessee", nameField: "tenant_name", typeField: "tenant_type", addressField: "tenant_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  schedules: [
    {
      id: "schedule_premises",
      title: "SCHEDULE OF LEASED PROPERTY",
      descriptionField: "property_address",
      boundariesFields: {
        north: "boundary_north",
        south: "boundary_south",
        east: "boundary_east",
        west: "boundary_west",
      },
    },
  ],
  steps: [
    { id: "type", title: "Document type", description: "Standard TN Tenancy Format", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Landlord & Tenant", description: "Names, ID details, and addresses", fieldIds: ["landlord_name", "landlord_type", "landlord_address", "tenant_name", "tenant_type", "tenant_address"] },
    { id: "premises", title: "Premises & Boundaries", description: "Property address, use, and 4-side boundaries", fieldIds: ["property_address", "property_use", "boundary_north", "boundary_south", "boundary_east", "boundary_west"] },
    { id: "financial", title: "Rent & Deposit", description: "Monthly rent, advance/deposit, and due date", fieldIds: ["rent_amount", "deposit_amount", "rent_due_day"] },
    { id: "tenure", title: "Tenancy Period", description: "Commencement date and duration in months", fieldIds: ["effective_date", "duration_months", "end_date", "termination_notice_days"] },
    { id: "witnesses", title: "Witness Attestation", description: "Particulars of two independent witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("landlord_name", "Landlord full name", "LANDLORD FULL NAME", "text", "required", "parties"),
    field("landlord_type", "Landlord entity type", "LANDLORD TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("landlord_address", "Landlord permanent address", "LANDLORD PERMANENT ADDRESS", "textarea", "required", "parties"),
    field("tenant_name", "Tenant full name", "TENANT FULL NAME", "text", "required", "parties"),
    field("tenant_type", "Tenant entity type", "TENANT TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("tenant_address", "Tenant permanent address", "TENANT PERMANENT ADDRESS", "textarea", "required", "parties"),
    field("property_address", "Full address of premises", "LEASED PREMISES ADDRESS", "textarea", "required", "premises"),
    field("property_use", "Premises use", "PREMISES USE", "select", "required", "premises", {
      options: [
        { value: "residential", label: "Residential purposes only" },
        { value: "commercial", label: "Commercial / Office use" },
      ],
    }),
    field("boundary_north", "North boundary", "NORTH BOUNDARY", "text", "recommended", "premises"),
    field("boundary_south", "South boundary", "SOUTH BOUNDARY", "text", "recommended", "premises"),
    field("boundary_east", "East boundary", "EAST BOUNDARY", "text", "recommended", "premises"),
    field("boundary_west", "West boundary", "WEST BOUNDARY", "text", "recommended", "premises"),
    field("rent_amount", "Monthly rent (₹ INR)", "MONTHLY RENT", "currency", "required", "financial"),
    field("deposit_amount", "Interest-free security deposit (₹ INR)", "SECURITY DEPOSIT", "currency", "required", "financial"),
    field("rent_due_day", "Rent due date (Day of month)", "RENT DUE DAY", "number", "recommended", "financial", { min: 1, max: 28 }),
    field("effective_date", "Tenancy commencement date", "COMMENCEMENT DATE", "date", "required", "tenure"),
    field("duration_months", "Tenancy period in months", "TENANCY PERIOD", "number", "required", "tenure", { min: 1, max: 36 }),
    field("end_date", "Tenancy expiration date", "EXPIRATION DATE", "date", "recommended", "tenure"),
    field("termination_notice_days", "Termination notice period (days)", "NOTICE PERIOD", "number", "recommended", "tenure", { min: 15, max: 90 }),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "TITLE & PREAMBLE", required: true },
    { id: "demise", title: "1. Demise and Leased Premises", required: true },
    { id: "term", title: "2. Period of Tenancy and Renewal", required: true },
    { id: "rent_deposit", title: "3. Monthly Rent and Security Deposit", required: true },
    { id: "maintenance", title: "4. Maintenance, Utilities and Municipal Charges", required: true },
    { id: "covenants", title: "5. Tenant Covenants and Restrictions", required: true },
    { id: "termination", title: "6. Termination and Handover of Peaceful Vacant Possession", required: true },
    { id: "dispute_resolution", title: "7. Governing Law and Jurisdiction", required: true, needsLegalContext: true },
    { id: "schedule_property", title: "SCHEDULE OF PREMISES", required: true },
    { id: "attestation", title: "IN WITNESS WHEREOF & ATTESTATION", required: true, includeSignature: true },
  ],
};

export const SALE_DEED_TEMPLATE: TemplateSpec = {
  id: "sale_deed",
  category: "deed",
  title: "Absolute Sale Deed (விற்பனை கிரைய பத்திரம்)",
  description: "Conveyance deed for absolute transfer of immovable property with title recitals, encumbrance indemnity, and boundary schedules.",
  documentType: "Deed of Absolute Sale",
  jurisdictionCountry: "IN",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "State Registration Department Model Forms under Registration Act 1908",
    document_name: "Model Deed of Absolute Sale of Immovable Property",
    reference_date: "2026-01-01",
  },
  applicability: "Sale of residential land, flat, or commercial immovable property across India.",
  executionRequirements: [
    "To be printed on stamp paper of value prescribed by State Stamp Act",
    "Mandatory registration under Section 17 of the Registration Act, 1908 within 4 months of execution",
    "Signed by Vendor and Purchaser on every sheet",
    "Two credible witnesses to identify parties and attest signatures before Sub-Registrar",
  ],
  parties: [
    { id: "vendor", role: "Vendor / Seller", nameField: "vendor_name", typeField: "vendor_type", addressField: "vendor_address" },
    { id: "purchaser", role: "Purchaser / Buyer", nameField: "purchaser_name", typeField: "purchaser_type", addressField: "purchaser_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  schedules: [
    {
      id: "schedule_property",
      title: "SCHEDULE OF CONVEYED PROPERTY",
      descriptionField: "property_address",
      boundariesFields: {
        north: "boundary_north",
        south: "boundary_south",
        east: "boundary_east",
        west: "boundary_west",
      },
    },
  ],
  steps: [
    { id: "type", title: "Deed Type", description: "Conveyance deed", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction & Sub-Registrar", description: "State & District", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Vendor & Purchaser", description: "Full legal names and addresses", fieldIds: ["vendor_name", "vendor_type", "vendor_address", "purchaser_name", "purchaser_type", "purchaser_address"] },
    { id: "consideration", title: "Sale Price & Payment", description: "Total consideration and payment mode", fieldIds: ["sale_consideration", "payment_mode", "earnest_deposit", "effective_date"] },
    { id: "property", title: "Property Description & Boundaries", description: "Survey/plot numbers and 4 boundaries", fieldIds: ["property_address", "property_extent", "survey_number", "boundary_north", "boundary_south", "boundary_east", "boundary_west"] },
    { id: "witnesses", title: "Witness Attestation", description: "Particulars of two witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("vendor_name", "Vendor / Seller full name", "VENDOR FULL NAME", "text", "required", "parties"),
    field("vendor_type", "Vendor entity type", "VENDOR TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("vendor_address", "Vendor permanent address", "VENDOR ADDRESS", "textarea", "required", "parties"),
    field("purchaser_name", "Purchaser / Buyer full name", "PURCHASER FULL NAME", "text", "required", "parties"),
    field("purchaser_type", "Purchaser entity type", "PURCHASER TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("purchaser_address", "Purchaser permanent address", "PURCHASER ADDRESS", "textarea", "required", "parties"),
    field("sale_consideration", "Total sale consideration (₹ INR)", "SALE CONSIDERATION", "currency", "required", "consideration"),
    field("payment_mode", "Mode of payment / Cheque / DD / RTGS details", "PAYMENT DETAILS", "textarea", "required", "consideration"),
    field("earnest_deposit", "Earnest money / Advance paid (₹ INR)", "EARNEST MONEY", "currency", "recommended", "consideration"),
    field("effective_date", "Date of deed execution", "EXECUTION DATE", "date", "required", "consideration"),
    field("property_address", "Complete description of immovable property", "PROPERTY DESCRIPTION", "textarea", "required", "property"),
    field("property_extent", "Extent / Area of property (sq.ft / cents / acres)", "PROPERTY EXTENT", "text", "required", "property"),
    field("survey_number", "Survey / Town Survey / Patta Number", "SURVEY NUMBER", "text", "required", "property"),
    field("boundary_north", "Bounded on the North by", "NORTH BOUNDARY", "text", "required", "property"),
    field("boundary_south", "Bounded on the South by", "SOUTH BOUNDARY", "text", "required", "property"),
    field("boundary_east", "Bounded on the East by", "EAST BOUNDARY", "text", "required", "property"),
    field("boundary_west", "Bounded on the West by", "WEST BOUNDARY", "text", "required", "property"),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "DEED OF ABSOLUTE SALE", required: true },
    { id: "recitals", title: "Recitals of Title Derivation", required: true },
    { id: "consideration_receipt", title: "1. Sale Consideration and Receipt", required: true },
    { id: "conveyance", title: "2. Grant and Absolute Conveyance", required: true },
    { id: "possession", title: "3. Delivery of Absolute Vacant Possession", required: true },
    { id: "covenant_encumbrance", title: "4. Covenant of Free Title and Indemnity Against Encumbrances", required: true },
    { id: "title_deeds", title: "5. Production and Delivery of Title Deeds", required: true },
    { id: "statutory_dues", title: "6. Payment of Taxes and Statutory Outgoings", required: true },
    { id: "schedule_property", title: "SCHEDULE OF CONVEYED PROPERTY", required: true },
    { id: "attestation", title: "EXECUTION & ATTESTATION BY WITNESSES", required: true, includeSignature: true },
  ],
};

export const GENERAL_POWER_OF_ATTORNEY_TEMPLATE: TemplateSpec = {
  id: "general_power_of_attorney",
  category: "deed",
  title: "General Power of Attorney (பொது அதிகார ஆவணம்)",
  description: "General Power of Attorney empowering an attorney to manage property, institute legal proceedings, and execute instruments.",
  documentType: "General Power of Attorney",
  jurisdictionCountry: "IN",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "Powers of Attorney Act, 1882 & Registration Act, 1908",
    document_name: "Model General Power of Attorney Deed",
    reference_date: "2026-01-01",
  },
  applicability: "Empowering trusted agent for administrative, financial, property management, and litigation matters across India.",
  executionRequirements: [
    "To be executed on non-judicial stamp paper of prescribed value under state stamp laws",
    "Must be authenticated before a Notary Public, Magistrate, or Sub-Registrar under Section 85 of Evidence Act",
    "If power relates to sale/conveyance of immovable property, registration under Registration Act is compulsory",
  ],
  parties: [
    { id: "principal", role: "Principal", nameField: "principal_name", typeField: "principal_type", addressField: "principal_address" },
    { id: "attorney", role: "Attorney / Agent", nameField: "attorney_name", typeField: "attorney_type", addressField: "attorney_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  steps: [
    { id: "type", title: "Deed Type", description: "General Power of Attorney", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Principal & Attorney", description: "Full identities and addresses", fieldIds: ["principal_name", "principal_type", "principal_address", "attorney_name", "attorney_type", "attorney_address"] },
    { id: "purpose", title: "Purpose & Powers", description: "Reason for delegation and effective date", fieldIds: ["purpose", "effective_date"] },
    { id: "witnesses", title: "Witness Attestation", description: "Two witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("principal_name", "Principal full name", "PRINCIPAL FULL NAME", "text", "required", "parties"),
    field("principal_type", "Principal type", "PRINCIPAL TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("principal_address", "Principal permanent address", "PRINCIPAL ADDRESS", "textarea", "required", "parties"),
    field("attorney_name", "Attorney / Agent full name", "ATTORNEY FULL NAME", "text", "required", "parties"),
    field("attorney_type", "Attorney type", "ATTORNEY TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("attorney_address", "Attorney permanent address", "ATTORNEY ADDRESS", "textarea", "required", "parties"),
    field("purpose", "Reason for delegation of power", "PURPOSE", "textarea", "required", "purpose"),
    field("effective_date", "Date of execution", "DATE OF EXECUTION", "date", "required", "purpose"),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "GENERAL POWER OF ATTORNEY", required: true },
    { id: "appointment", title: "1. Appointment and Constitution of Attorney", required: true },
    { id: "powers_management", title: "2. Powers of Property Management and Administration", required: true },
    { id: "powers_litigation", title: "3. Powers of Legal Representation and Litigation", required: true },
    { id: "powers_statutory", title: "4. Representation before Government & Municipal Authorities", required: true },
    { id: "ratification", title: "5. Ratification and Confirmation", required: true },
    { id: "revocation_terms", title: "6. Revocation and Non-Transferability", required: true },
    { id: "attestation", title: "IN WITNESS WHEREOF & ATTESTATION", required: true, includeSignature: true },
  ],
};

export const SPECIAL_POWER_OF_ATTORNEY_TEMPLATE: TemplateSpec = {
  id: "special_power_of_attorney",
  category: "deed",
  title: "Special Power of Attorney (குறிப்பிட்ட அதிகார ஆவணம்)",
  description: "Specific power of attorney authorizing an agent to perform designated acts for a single legal or property transaction.",
  documentType: "Special Power of Attorney",
  jurisdictionCountry: "IN",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "Powers of Attorney Act, 1882",
    document_name: "Model Special Power of Attorney for Specific Act",
    reference_date: "2026-01-01",
  },
  applicability: "Specific single transactions (registration of deed, court appearance, vehicle transfer, bank transaction).",
  executionRequirements: [
    "To be executed on non-judicial stamp paper of prescribed denomination",
    "Notarized before a Notary Public with notarial stamp and seal",
  ],
  parties: [
    { id: "principal", role: "Principal", nameField: "principal_name", typeField: "principal_type", addressField: "principal_address" },
    { id: "attorney", role: "Special Attorney", nameField: "attorney_name", typeField: "attorney_type", addressField: "attorney_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  steps: [
    { id: "type", title: "Document Type", description: "Special Power of Attorney", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Principal & Attorney", description: "Identities", fieldIds: ["principal_name", "principal_type", "principal_address", "attorney_name", "attorney_type", "attorney_address"] },
    { id: "purpose", title: "Specific Act Authorized", description: "Description of the single designated act", fieldIds: ["specific_act", "effective_date"] },
    { id: "witnesses", title: "Witnesses", description: "Attesting witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("principal_name", "Principal full name", "PRINCIPAL FULL NAME", "text", "required", "parties"),
    field("principal_type", "Principal type", "PRINCIPAL TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("principal_address", "Principal permanent address", "PRINCIPAL ADDRESS", "textarea", "required", "parties"),
    field("attorney_name", "Special attorney full name", "ATTORNEY FULL NAME", "text", "required", "parties"),
    field("attorney_type", "Attorney type", "ATTORNEY TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("attorney_address", "Attorney permanent address", "ATTORNEY ADDRESS", "textarea", "required", "parties"),
    field("specific_act", "Specific act and transaction authorized", "SPECIFIC AUTHORIZED ACT", "textarea", "required", "purpose"),
    field("effective_date", "Date of execution", "DATE OF EXECUTION", "date", "required", "purpose"),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "SPECIAL POWER OF ATTORNEY", required: true },
    { id: "appointment", title: "1. Appointment for Designated Purpose", required: true },
    { id: "specific_powers", title: "2. Specific Powers Granted", required: true },
    { id: "ratification", title: "3. Ratification of Authorized Acts", required: true },
    { id: "termination", title: "4. Expiry on Completion of Transaction", required: true },
    { id: "attestation", title: "IN WITNESS WHEREOF & ATTESTATION", required: true, includeSignature: true },
  ],
};

export const GIFT_DEED_TEMPLATE: TemplateSpec = {
  id: "gift_deed",
  category: "deed",
  title: "Gift Deed (தான செட்டில்மென்ட் பத்திரம்)",
  description: "Deed of gift transferring property voluntarily out of natural love and affection without monetary consideration.",
  documentType: "Deed of Gift",
  jurisdictionCountry: "IN",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "Section 122 of Transfer of Property Act, 1882",
    document_name: "Model Gift Deed of Immovable Property",
    reference_date: "2026-01-01",
  },
  applicability: "Transfer of property to family members or loved ones without consideration.",
  executionRequirements: [
    "Compulsory registration under Section 123 of Transfer of Property Act and Section 17 of Registration Act",
    "Must be attested by at least two witnesses who saw the donor sign",
    "Donee must formally accept the gift during donor's lifetime",
  ],
  parties: [
    { id: "donor", role: "Donor", nameField: "donor_name", typeField: "donor_type", addressField: "donor_address" },
    { id: "donee", role: "Donee", nameField: "donee_name", typeField: "donee_type", addressField: "donee_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  schedules: [
    {
      id: "schedule_property",
      title: "SCHEDULE OF GIFTED PROPERTY",
      descriptionField: "property_address",
      boundariesFields: {
        north: "boundary_north",
        south: "boundary_south",
        east: "boundary_east",
        west: "boundary_west",
      },
    },
  ],
  steps: [
    { id: "type", title: "Deed Type", description: "Deed of Gift", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & District", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Donor & Donee", description: "Identities and relationship", fieldIds: ["donor_name", "donor_type", "donor_address", "donee_name", "donee_type", "donee_address", "relationship"] },
    { id: "property", title: "Property Particulars", description: "Property address and boundaries", fieldIds: ["property_address", "boundary_north", "boundary_south", "boundary_east", "boundary_west", "effective_date"] },
    { id: "witnesses", title: "Witness Attestation", description: "Two witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("donor_name", "Donor full name", "DONOR FULL NAME", "text", "required", "parties"),
    field("donor_type", "Donor type", "DONOR TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("donor_address", "Donor permanent address", "DONOR ADDRESS", "textarea", "required", "parties"),
    field("donee_name", "Donee full name", "DONEE FULL NAME", "text", "required", "parties"),
    field("donee_type", "Donee type", "DONEE TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("donee_address", "Donee permanent address", "DONEE ADDRESS", "textarea", "required", "parties"),
    field("relationship", "Relationship between Donor and Donee", "RELATIONSHIP", "text", "required", "parties"),
    field("property_address", "Full description of gifted property", "GIFTED PROPERTY ADDRESS", "textarea", "required", "property"),
    field("boundary_north", "North boundary", "NORTH BOUNDARY", "text", "required", "property"),
    field("boundary_south", "South boundary", "SOUTH BOUNDARY", "text", "required", "property"),
    field("boundary_east", "East boundary", "EAST BOUNDARY", "text", "required", "property"),
    field("boundary_west", "West boundary", "WEST BOUNDARY", "text", "required", "property"),
    field("effective_date", "Date of gift execution", "EXECUTION DATE", "date", "required", "property"),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "DEED OF GIFT", required: true },
    { id: "recitals", title: "Recitals of Natural Love, Affection and Title", required: true },
    { id: "transfer", title: "1. Absolute Gift without Monetary Consideration", required: true },
    { id: "possession", title: "2. Delivery of Possession to Donee", required: true },
    { id: "acceptance", title: "3. Formal Acceptance by Donee", required: true },
    { id: "schedule_property", title: "SCHEDULE OF GIFTED PROPERTY", required: true },
    { id: "attestation", title: "EXECUTION & ATTESTATION BY WITNESSES", required: true, includeSignature: true },
  ],
};

export const RELEASE_DEED_TEMPLATE: TemplateSpec = {
  id: "release_deed",
  category: "deed",
  title: "Release Deed / Relinquishment Deed (விடுதலைப் பத்திரம்)",
  description: "Deed of release / relinquishment by a co-owner or legal heir renouncing right, title, and undivided share in joint property.",
  documentType: "Deed of Release / Relinquishment",
  jurisdictionCountry: "IN",
  language: ["English", "Tamil"],
  version: "2026.1",
  source: {
    authority: "Registration Act, 1908 & Transfer of Property Act, 1882",
    document_name: "Model Relinquishment Deed among Legal Heirs",
    reference_date: "2026-01-01",
  },
  applicability: "Relinquishing ancestral or joint property shares in favour of co-heirs.",
  executionRequirements: [
    "Compulsory registration under Section 17 of the Registration Act, 1908",
    "Proper stamp duty as prescribed by State amendment for family release",
    "Two witnesses required for execution",
  ],
  parties: [
    { id: "releasor", role: "Releasor / Relinquisher", nameField: "releasor_name", typeField: "releasor_type", addressField: "releasor_address" },
    { id: "releasee", role: "Releasee / Beneficiary", nameField: "releasee_name", typeField: "releasee_type", addressField: "releasee_address" },
  ],
  witnesses: [
    { id: "witness_1", role: "Witness 1", nameField: "witness_1_name", addressField: "witness_1_address" },
    { id: "witness_2", role: "Witness 2", nameField: "witness_2_name", addressField: "witness_2_address" },
  ],
  steps: [
    { id: "type", title: "Deed Type", description: "Release Deed", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & District", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Releasor & Releasee", description: "Heir particulars", fieldIds: ["releasor_name", "releasor_type", "releasor_address", "releasee_name", "releasee_type", "releasee_address", "relationship"] },
    { id: "property", title: "Property & Share", description: "Joint property description", fieldIds: ["property_address", "share_description", "effective_date"] },
    { id: "witnesses", title: "Witnesses", description: "Attesting witnesses", fieldIds: ["witness_1_name", "witness_1_address", "witness_2_name", "witness_2_address"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("releasor_name", "Releasor full name", "RELEASOR FULL NAME", "text", "required", "parties"),
    field("releasor_type", "Releasor type", "RELEASOR TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("releasor_address", "Releasor permanent address", "RELEASOR ADDRESS", "textarea", "required", "parties"),
    field("releasee_name", "Releasee full name", "RELEASEE FULL NAME", "text", "required", "parties"),
    field("releasee_type", "Releasee type", "RELEASEE TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("releasee_address", "Releasee permanent address", "RELEASEE ADDRESS", "textarea", "required", "parties"),
    field("relationship", "Relationship of parties (e.g. Brother and Sister)", "RELATIONSHIP", "text", "required", "parties"),
    field("property_address", "Description of joint property", "JOINT PROPERTY ADDRESS", "textarea", "required", "property"),
    field("share_description", "Undivided share being released (e.g. 1/3rd share)", "SHARE RELEASED", "text", "required", "property"),
    field("effective_date", "Date of deed execution", "EXECUTION DATE", "date", "required", "property"),
    field("witness_1_name", "Witness 1 name", "WITNESS 1 NAME", "text", "recommended", "witnesses"),
    field("witness_1_address", "Witness 1 address", "WITNESS 1 ADDRESS", "textarea", "recommended", "witnesses"),
    field("witness_2_name", "Witness 2 name", "WITNESS 2 NAME", "text", "recommended", "witnesses"),
    field("witness_2_address", "Witness 2 address", "WITNESS 2 ADDRESS", "textarea", "recommended", "witnesses"),
  ],
  clauses: [
    { id: "title", title: "DEED OF RELEASE", required: true },
    { id: "recitals", title: "Recitals of Joint Devolution and Co-Ownership", required: true },
    { id: "release_clause", title: "1. Absolute Relinquishment and Renunciation of Share", required: true },
    { id: "covenant_further", title: "2. Covenant of Non-Claim and Perfect Title", required: true },
    { id: "schedule_property", title: "SCHEDULE OF IMMOVABLE PROPERTY", required: true },
    { id: "attestation", title: "IN WITNESS WHEREOF & ATTESTATION", required: true, includeSignature: true },
  ],
};

export const COMMERCIAL_LEASE_TEMPLATE: TemplateSpec = {
  id: "commercial_lease",
  category: "agreement",
  title: "Commercial Lease Agreement",
  description: "Commercial lease agreement for office, showroom, or retail premises with lock-in, escalation, CAM charges, and GST clauses.",
  documentType: "Commercial Lease Agreement",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Model Commercial Lease Standards under Transfer of Property Act, 1882",
    document_name: "Standard Commercial Lease Agreement",
    reference_date: "2026-01-01",
  },
  applicability: "Leasing retail shops, corporate offices, warehouses, or industrial spaces.",
  executionRequirements: [
    "Stamp duty applicable per State Stamp Act for commercial leases",
    "Compulsory registration under Section 107 of Transfer of Property Act if lease term exceeds 11 months",
  ],
  parties: [
    { id: "lessor", role: "Lessor / Landlord", nameField: "lessor_name", typeField: "lessor_type", addressField: "lessor_address" },
    { id: "lessee", role: "Lessee / Tenant", nameField: "lessee_name", typeField: "lessee_type", addressField: "lessee_address" },
  ],
  steps: [
    { id: "type", title: "Document Type", description: "Commercial lease", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Lessor & Lessee", description: "Corporate and individual parties", fieldIds: ["lessor_name", "lessor_type", "lessor_address", "lessee_name", "lessee_type", "lessee_address"] },
    { id: "premises", title: "Commercial Premises", description: "Address, super built-up area, and permitted use", fieldIds: ["property_address", "area_sqft", "business_nature"] },
    { id: "financial", title: "Rent, CAM & Deposit", description: "Base rent, escalation %, CAM, security deposit", fieldIds: ["rent_amount", "cam_charges", "escalation_percent", "deposit_amount"] },
    { id: "tenure", title: "Term & Lock-in", description: "Lease period and lock-in period", fieldIds: ["effective_date", "lease_years", "lock_in_months", "termination_notice_days"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("lessor_name", "Lessor full name / company name", "LESSOR NAME", "text", "required", "parties"),
    field("lessor_type", "Lessor entity type", "LESSOR TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("lessor_address", "Lessor registered address", "LESSOR ADDRESS", "textarea", "required", "parties"),
    field("lessee_name", "Lessee full name / company name", "LESSEE NAME", "text", "required", "parties"),
    field("lessee_type", "Lessee entity type", "LESSEE TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("lessee_address", "Lessee registered address", "LESSEE ADDRESS", "textarea", "required", "parties"),
    field("property_address", "Full address of commercial premises", "COMMERCIAL PREMISES ADDRESS", "textarea", "required", "premises"),
    field("area_sqft", "Super built-up / chargeable area in sq.ft", "AREA IN SQ FT", "number", "required", "premises"),
    field("business_nature", "Permitted commercial use / business", "PERMITTED BUSINESS USE", "textarea", "required", "premises"),
    field("rent_amount", "Monthly lease rent (₹ INR)", "MONTHLY RENT", "currency", "required", "financial"),
    field("cam_charges", "Common Area Maintenance (CAM) charges (₹ INR/mo)", "CAM CHARGES", "currency", "recommended", "financial"),
    field("escalation_percent", "Rent escalation % per annum / cycle", "ESCALATION PERCENT", "number", "recommended", "financial"),
    field("deposit_amount", "Interest-free refundable security deposit (₹ INR)", "SECURITY DEPOSIT", "currency", "required", "financial"),
    field("effective_date", "Lease commencement date", "COMMENCEMENT DATE", "date", "required", "tenure"),
    field("lease_years", "Lease duration in years", "LEASE YEARS", "number", "required", "tenure", { min: 1, max: 30 }),
    field("lock_in_months", "Lock-in period in months", "LOCK-IN MONTHS", "number", "recommended", "tenure"),
    field("termination_notice_days", "Termination notice period (days)", "NOTICE DAYS", "number", "recommended", "tenure"),
  ],
  clauses: [
    { id: "title", title: "COMMERCIAL LEASE AGREEMENT", required: true },
    { id: "demise", title: "1. Demise and Leased Space", required: true },
    { id: "term_lockin", title: "2. Lease Term, Commencement and Lock-in Period", required: true },
    { id: "rent_escalation", title: "3. Monthly Rent, GST and Escalation", required: true },
    { id: "cam_utilities", title: "4. CAM Charges, Electricity and Municipal Rates", required: true },
    { id: "security_deposit", title: "5. Security Deposit Terms and Refund", required: true },
    { id: "permitted_use", title: "6. Permitted Use, Approvals and Compliance", required: true },
    { id: "termination", title: "7. Termination and Handover of Possession", required: true },
    { id: "dispute_resolution", title: "8. Dispute Resolution and Governing Law", required: true, needsLegalContext: true },
    { id: "signatures", title: "IN WITNESS WHEREOF", required: true, includeSignature: true },
  ],
};

export const LEAVE_LICENSE_TEMPLATE: TemplateSpec = {
  id: "leave_license",
  category: "agreement",
  title: "Leave and License Agreement",
  description: "Standard Leave and License Agreement under Indian Easements Act, 1882 granting permissive occupancy without tenancy rights.",
  documentType: "Leave and License Agreement",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Section 52 of Indian Easements Act, 1882 & Maharashtra Rent Control Act, 1999 Model Rules",
    document_name: "Model Leave and License Agreement",
    reference_date: "2026-01-01",
  },
  applicability: "Residential permissive occupation especially in Maharashtra, Karnataka, and urban centers.",
  executionRequirements: [
    "Compulsory registration in Maharashtra under Section 55 of Maharashtra Rent Control Act, 1999",
    "Proper stamp duty per State stamp legislation",
  ],
  parties: [
    { id: "licensor", role: "Licensor", nameField: "licensor_name", typeField: "licensor_type", addressField: "licensor_address" },
    { id: "licensee", role: "Licensee", nameField: "licensee_name", typeField: "licensee_type", addressField: "licensee_address" },
  ],
  steps: [
    { id: "type", title: "Document Type", description: "Leave and License", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Licensor & Licensee", description: "Parties particulars", fieldIds: ["licensor_name", "licensor_type", "licensor_address", "licensee_name", "licensee_type", "licensee_address"] },
    { id: "premises", title: "Licensed Premises", description: "Address and use", fieldIds: ["property_address", "property_use"] },
    { id: "financial", title: "License Fee & Deposit", description: "Monthly fee and security deposit", fieldIds: ["license_fee", "deposit_amount"] },
    { id: "tenure", title: "Term", description: "Commencement date and duration in months", fieldIds: ["effective_date", "duration_months", "termination_notice_days"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("licensor_name", "Licensor full name", "LICENSOR NAME", "text", "required", "parties"),
    field("licensor_type", "Licensor type", "LICENSOR TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("licensor_address", "Licensor address", "LICENSOR ADDRESS", "textarea", "required", "parties"),
    field("licensee_name", "Licensee full name", "LICENSEE NAME", "text", "required", "parties"),
    field("licensee_type", "Licensee type", "LICENSEE TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("licensee_address", "Licensee address", "LICENSEE ADDRESS", "textarea", "required", "parties"),
    field("property_address", "Full address of licensed premises", "LICENSED PREMISES ADDRESS", "textarea", "required", "premises"),
    field("property_use", "Purpose of license (Residential / Commercial)", "PREMISES USE", "text", "required", "premises"),
    field("license_fee", "Monthly license fee (₹ INR)", "MONTHLY LICENSE FEE", "currency", "required", "financial"),
    field("deposit_amount", "Security deposit (₹ INR)", "SECURITY DEPOSIT", "currency", "required", "financial"),
    field("effective_date", "License start date", "START DATE", "date", "required", "tenure"),
    field("duration_months", "License duration (months)", "DURATION MONTHS", "number", "required", "tenure", { min: 1, max: 60 }),
    field("termination_notice_days", "Notice period for termination (days)", "NOTICE DAYS", "number", "recommended", "tenure"),
  ],
  clauses: [
    { id: "title", title: "LEAVE AND LICENSE AGREEMENT", required: true },
    { id: "grant", title: "1. Grant of Pure License and Disavowal of Tenancy", required: true },
    { id: "term", title: "2. Term and Duration of License", required: true },
    { id: "fee_deposit", title: "3. Monthly Compensation / License Fee and Security Deposit", required: true },
    { id: "licensee_obligations", title: "4. Licensee Undertakings and Covenants", required: true },
    { id: "revocation", title: "5. Revocation, Termination and Vacant Possession", required: true },
    { id: "dispute_resolution", title: "6. Jurisdiction and Governing Law", required: true, needsLegalContext: true },
    { id: "signatures", title: "IN WITNESS WHEREOF", required: true, includeSignature: true },
  ],
};

export const LOAN_AGREEMENT_TEMPLATE: TemplateSpec = {
  id: "loan_agreement",
  category: "agreement",
  title: "Loan Agreement (Bilateral Money Lending Agreement)",
  description: "Bilateral loan agreement between lender and borrower specifying principal, interest, repayment schedule, and default consequences.",
  documentType: "Loan Agreement",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Indian Contract Act, 1872 & Negotiable Instruments Act, 1881",
    document_name: "Model Bilateral Loan Agreement",
    reference_date: "2026-01-01",
  },
  applicability: "Personal loans, promissory loan facilities, or friendly loans between individuals or non-banking entities.",
  executionRequirements: [
    "Executed on stamp paper of appropriate value",
    "Demand promissory note may be executed as collateral security",
  ],
  parties: [
    { id: "lender", role: "Lender", nameField: "lender_name", typeField: "lender_type", addressField: "lender_address" },
    { id: "borrower", role: "Borrower", nameField: "borrower_name", typeField: "borrower_type", addressField: "borrower_address" },
  ],
  steps: [
    { id: "type", title: "Document Type", description: "Loan Agreement", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Lender & Borrower", description: "Parties particulars", fieldIds: ["lender_name", "lender_type", "lender_address", "borrower_name", "borrower_type", "borrower_address"] },
    { id: "loan_terms", title: "Loan Amount & Interest", description: "Principal, rate of interest, disbursal date", fieldIds: ["loan_amount", "interest_rate_percent", "effective_date"] },
    { id: "repayment", title: "Repayment Schedule", description: "Tenure, monthly installment, maturity date", fieldIds: ["tenure_months", "repayment_terms", "default_interest_percent"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("lender_name", "Lender full name", "LENDER NAME", "text", "required", "parties"),
    field("lender_type", "Lender type", "LENDER TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("lender_address", "Lender address", "LENDER ADDRESS", "textarea", "required", "parties"),
    field("borrower_name", "Borrower full name", "BORROWER NAME", "text", "required", "parties"),
    field("borrower_type", "Borrower type", "BORROWER TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("borrower_address", "Borrower address", "BORROWER ADDRESS", "textarea", "required", "parties"),
    field("loan_amount", "Principal loan amount (₹ INR)", "LOAN PRINCIPAL AMOUNT", "currency", "required", "loan_terms"),
    field("interest_rate_percent", "Interest rate per annum (%)", "INTEREST RATE", "number", "required", "loan_terms"),
    field("effective_date", "Date of loan disbursal / agreement", "DISBURSAL DATE", "date", "required", "loan_terms"),
    field("tenure_months", "Loan repayment period (months)", "TENURE MONTHS", "number", "required", "repayment"),
    field("repayment_terms", "Repayment mode & installments (e.g. Monthly EMI or Bullet repayment)", "REPAYMENT TERMS", "textarea", "required", "repayment"),
    field("default_interest_percent", "Default / penal interest rate (% p.a.)", "PENAL INTEREST", "number", "recommended", "repayment"),
  ],
  clauses: [
    { id: "title", title: "LOAN AGREEMENT", required: true },
    { id: "disbursal", title: "1. Principal Loan Amount and Disbursal", required: true },
    { id: "interest_terms", title: "2. Interest Rate and Calculation", required: true },
    { id: "repayment_clause", title: "3. Repayment Schedule and Prepayment", required: true },
    { id: "default_events", title: "4. Events of Default and Penal Interest", required: true },
    { id: "remedies", title: "5. Acceleration and Recovery Rights", required: true },
    { id: "governing_law", title: "6. Governing Law and Jurisdiction", required: true, needsLegalContext: true },
    { id: "signatures", title: "IN WITNESS WHEREOF", required: true, includeSignature: true },
  ],
};

export const RTI_APPLICATION_TEMPLATE: TemplateSpec = {
  id: "rti_application",
  category: "application",
  title: "RTI Application (Form A under Right to Information Act, 2005)",
  description: "Statutory application under Section 6(1) of Right to Information Act, 2005 seeking official information from Public Information Officer.",
  documentType: "Application under RTI Act, 2005",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Right to Information Act, 2005 & Central/State RTI Rules",
    document_name: "Form A - Application for Information under Section 6(1)",
    reference_date: "2026-01-01",
  },
  applicability: "Citizens seeking public records from Central or State government departments.",
  executionRequirements: [
    "Accompanied by application fee (₹10 for Central authorities via IPO / Court Fee Stamp / DD / Online)",
    "Must be addressed to designated Central/State Public Information Officer (CPIO / SPIO)",
  ],
  parties: [
    { id: "applicant", role: "Applicant", nameField: "applicant_name", typeField: "applicant_type", addressField: "applicant_address" },
    { id: "authority", role: "Public Information Officer", nameField: "pio_designation", typeField: "authority_type", addressField: "department_address" },
  ],
  steps: [
    { id: "type", title: "RTI Request", description: "Section 6(1) Application", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "Central / State Department", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "authority", title: "Public Information Officer", description: "PIO Designation & Department Address", fieldIds: ["pio_designation", "public_authority_name", "department_address"] },
    { id: "applicant", title: "Applicant Details", description: "Name, address, contact details", fieldIds: ["applicant_name", "applicant_address", "applicant_phone"] },
    { id: "queries", title: "Information Sought", description: "Specific itemized questions & time period", fieldIds: ["specific_queries", "period_of_info", "effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("pio_designation", "Designation of PIO (e.g. Public Information Officer)", "PIO DESIGNATION", "text", "required", "authority"),
    field("public_authority_name", "Public Authority / Ministry / Department name", "PUBLIC AUTHORITY", "text", "required", "authority"),
    field("department_address", "Address of Public Authority", "AUTHORITY ADDRESS", "textarea", "required", "authority"),
    field("applicant_name", "Applicant full name", "APPLICANT NAME", "text", "required", "applicant"),
    field("applicant_type", "Applicant category", "APPLICANT CATEGORY", "select", "required", "applicant", {
      options: [
        { value: "individual", label: "Citizen of India (Individual)" },
        { value: "bpl", label: "Below Poverty Line (Fee Exempt)" },
      ],
    }),
    field("applicant_address", "Applicant postal address", "APPLICANT POSTAL ADDRESS", "textarea", "required", "applicant"),
    field("applicant_phone", "Applicant telephone / mobile number", "APPLICANT PHONE", "tel", "recommended", "applicant"),
    field("specific_queries", "Particulars of information sought (numbered points)", "INFORMATION QUERIES", "textarea", "required", "queries"),
    field("period_of_info", "Period to which the information relates", "PERIOD OF INFORMATION", "text", "recommended", "queries"),
    field("effective_date", "Date of application", "DATE OF APPLICATION", "date", "required", "queries"),
  ],
  clauses: [
    { id: "heading", title: "FORM A — APPLICATION FOR INFORMATION UNDER SECTION 6(1)", required: true },
    { id: "particulars_applicant", title: "1. Particulars of the Applicant", required: true },
    { id: "particulars_info", title: "2. Particulars of Information Sought", required: true },
    { id: "citizenship_declaration", title: "3. Declaration of Indian Citizenship & Fee Particulars", required: true },
    { id: "signatures", title: "APPLICANT SIGNATURE", required: true, includeSignature: true },
  ],
};

export const LEGAL_AID_APPLICATION_TEMPLATE: TemplateSpec = {
  id: "legal_aid_application",
  category: "application",
  title: "Legal Aid Application (NALSA / DLSA Model Form)",
  description: "Application for free legal services under Section 12 of the Legal Services Authorities Act, 1987 to DLSA / TLSC / HCLSC.",
  documentType: "Application for Free Legal Aid",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "National Legal Services Authority (NALSA) Regulations, 2010",
    document_name: "Application Form for Free Legal Services under Section 12 of LSA Act",
    reference_date: "2026-01-01",
  },
  applicability: "Eligible persons (SC/ST, women, children, persons with disabilities, custody, income ceiling).",
  executionRequirements: [
    "No court fee or stamp duty payable",
    "To be submitted to District Legal Services Authority (DLSA) or Taluk Legal Services Committee (TLSC)",
  ],
  parties: [
    { id: "applicant", role: "Applicant", nameField: "applicant_name", typeField: "eligibility_category", addressField: "applicant_address" },
  ],
  steps: [
    { id: "type", title: "Legal Aid", description: "Application under Section 12", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction & Authority", description: "DLSA / TLSC Name", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "applicant", title: "Applicant Details", description: "Identity, eligibility category, and income", fieldIds: ["applicant_name", "eligibility_category", "applicant_address", "annual_income"] },
    { id: "matter", title: "Case Details", description: "Nature of dispute and legal aid requested", fieldIds: ["matter_summary", "relief_requested", "effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("applicant_name", "Applicant full name", "APPLICANT NAME", "text", "required", "applicant"),
    field("eligibility_category", "Eligibility category under Section 12", "ELIGIBILITY CATEGORY", "select", "required", "applicant", {
      options: [
        { value: "woman_child", label: "Woman or Child" },
        { value: "sc_st", label: "Member of SC or ST" },
        { value: "income_eligible", label: "Annual income below statutory ceiling" },
        { value: "custody", label: "Person in custody / detention" },
        { value: "disability", label: "Person with disability / mental illness" },
        { value: "disaster_victim", label: "Victim of mass disaster / violence" },
      ],
    }),
    field("applicant_address", "Applicant permanent address", "APPLICANT ADDRESS", "textarea", "required", "applicant"),
    field("annual_income", "Annual income (₹ INR)", "ANNUAL INCOME", "currency", "recommended", "applicant"),
    field("matter_summary", "Brief facts of the legal dispute / case", "DISPUTE SUMMARY", "textarea", "required", "matter"),
    field("relief_requested", "Type of legal aid requested (e.g. Advocate appointment / court fees)", "LEGAL AID TYPE", "textarea", "required", "matter"),
    field("effective_date", "Date of application", "DATE", "date", "required", "matter"),
  ],
  clauses: [
    { id: "heading", title: "BEFORE THE SECRETARY, DISTRICT LEGAL SERVICES AUTHORITY", required: true },
    { id: "applicant_particulars", title: "1. Particulars and Eligibility of Applicant", required: true },
    { id: "case_facts", title: "2. Facts of the Case / Grievance", required: true },
    { id: "prayer", title: "3. Prayer for Free Legal Aid and Representation", required: true },
    { id: "verification", title: "VERIFICATION ON SOLEMN AFFIRMATION", required: true, includeSignature: true },
  ],
};

export const PAYMENT_DEMAND_NOTICE_TEMPLATE: TemplateSpec = {
  id: "payment_demand_notice",
  category: "notice",
  title: "Cheque Bounce Notice (Demand Notice under Section 138 of NI Act)",
  description: "Statutory demand notice under Section 138(b) of Negotiable Instruments Act, 1881 calling upon drawer to pay dishonoured cheque amount within 15 days.",
  documentType: "Statutory Demand Notice under Section 138 NI Act",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Section 138(b) of Negotiable Instruments Act, 1881",
    document_name: "Statutory 15-Day Demand Notice for Dishonour of Cheque",
    reference_date: "2026-01-01",
  },
  applicability: "Dishonour of cheques due to insufficient funds or account closed.",
  executionRequirements: [
    "Must be issued within 30 days of receiving bank memo of dishonour",
    "Must give clear 15 days from receipt to pay",
    "Must be dispatched by Registered Post AD or Speed Post",
  ],
  parties: [
    { id: "payee", role: "Payee / Holder in Due Course", nameField: "payee_name", typeField: "payee_type", addressField: "payee_address" },
    { id: "drawer", role: "Drawer / Accused", nameField: "drawer_name", typeField: "drawer_type", addressField: "drawer_address" },
  ],
  steps: [
    { id: "type", title: "Notice Type", description: "Section 138 NI Act Notice", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Payee & Drawer", description: "Names and addresses", fieldIds: ["payee_name", "payee_type", "payee_address", "drawer_name", "drawer_type", "drawer_address", "advocate_name"] },
    { id: "cheque", title: "Cheque & Dishonour Details", description: "Cheque number, amount, bank memo", fieldIds: ["cheque_number", "cheque_date", "cheque_amount", "bank_name", "dishonour_date", "dishonour_reason"] },
    { id: "demand", title: "Statutory Demand", description: "Notice date & 15-day compliance window", fieldIds: ["effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("advocate_name", "Advocate name issuing notice", "ADVOCATE NAME", "text", "required", "parties"),
    field("payee_name", "Payee / Client full name", "PAYEE NAME", "text", "required", "parties"),
    field("payee_type", "Payee entity type", "PAYEE TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("payee_address", "Payee address", "PAYEE ADDRESS", "textarea", "required", "parties"),
    field("drawer_name", "Drawer / Accused full name", "DRAWER NAME", "text", "required", "parties"),
    field("drawer_type", "Drawer entity type", "DRAWER TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("drawer_address", "Drawer postal address", "DRAWER ADDRESS", "textarea", "required", "parties"),
    field("cheque_number", "Cheque number (6 digits)", "CHEQUE NUMBER", "text", "required", "cheque"),
    field("cheque_date", "Date of cheque", "CHEQUE DATE", "date", "required", "cheque"),
    field("cheque_amount", "Cheque amount (₹ INR)", "CHEQUE AMOUNT", "currency", "required", "cheque"),
    field("bank_name", "Drawee bank & branch name", "DRAWEE BANK", "text", "required", "cheque"),
    field("dishonour_date", "Date of bank return memo", "MEMO DATE", "date", "required", "cheque"),
    field("dishonour_reason", "Reason for dishonour in memo (e.g. Funds Insufficient)", "RETURN REASON", "text", "required", "cheque"),
    field("effective_date", "Date of notice issuance", "NOTICE DATE", "date", "required", "demand"),
  ],
  clauses: [
    { id: "header", title: "BY REGISTERED POST WITH A.D. / SPEED POST — DEMAND NOTICE UNDER SECTION 138 OF NI ACT", required: true },
    { id: "instructions", title: "1. Instructions and Legal Representation", required: true },
    { id: "cheque_facts", title: "2. Issuance, Consideration and Presentment of Cheque", required: true },
    { id: "dishonour_memo", title: "3. Dishonour by Bank and Notice of Return", required: true },
    { id: "statutory_demand", title: "4. Statutory Demand for Payment within 15 Days", required: true },
    { id: "penal_consequences", title: "5. Consequences of Failure: Criminal Prosecution and Civil Remedies", required: true },
    { id: "signatures", title: "ADVOCATE SIGNATURE & POSTAL DISPATCH", required: true, includeSignature: true },
  ],
};

export const EVICTION_NOTICE_TEMPLATE: TemplateSpec = {
  id: "eviction_notice",
  category: "notice",
  title: "Tenant Eviction Notice (Notice to Quit under Section 106 of Transfer of Property Act)",
  description: "Landlord's statutory notice terminating tenancy and demanding delivery of vacant possession of premises under Section 106 of Transfer of Property Act, 1882.",
  documentType: "Notice to Vacate / Eviction Notice",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Section 106 of Transfer of Property Act, 1882",
    document_name: "Notice Terminating Tenancy and Demanding Vacant Possession",
    reference_date: "2026-01-01",
  },
  applicability: "Terminating month-to-month tenancies or leases where period has expired or breached.",
  executionRequirements: [
    "Must be dispatched by Registered Post AD or personally tendered",
    "Must give at least 15 days notice expiring with the end of the tenancy month (or 6 months for agricultural/manufacturing leases)",
  ],
  parties: [
    { id: "landlord", role: "Landlord / Lessor", nameField: "landlord_name", typeField: "landlord_type", addressField: "landlord_address" },
    { id: "tenant", role: "Tenant / Lessee", nameField: "tenant_name", typeField: "tenant_type", addressField: "tenant_address" },
  ],
  steps: [
    { id: "type", title: "Notice Type", description: "Section 106 Notice to Vacate", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Landlord & Tenant", description: "Names and addresses", fieldIds: ["landlord_name", "landlord_type", "landlord_address", "tenant_name", "tenant_type", "tenant_address"] },
    { id: "premises", title: "Leased Premises & Tenancy", description: "Address, rent, and grounds for eviction", fieldIds: ["property_address", "rent_amount", "eviction_grounds"] },
    { id: "demand", title: "Vacation Demand", description: "Notice date & vacation deadline", fieldIds: ["effective_date", "vacate_deadline"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("landlord_name", "Landlord full name", "LANDLORD NAME", "text", "required", "parties"),
    field("landlord_type", "Landlord type", "LANDLORD TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("landlord_address", "Landlord address", "LANDLORD ADDRESS", "textarea", "required", "parties"),
    field("tenant_name", "Tenant full name", "TENANT NAME", "text", "required", "parties"),
    field("tenant_type", "Tenant type", "TENANT TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("tenant_address", "Tenant premises address", "TENANT ADDRESS", "textarea", "required", "parties"),
    field("property_address", "Full address of tenanted premises", "TENANTED PREMISES", "textarea", "required", "premises"),
    field("rent_amount", "Agreed monthly rent (₹ INR)", "MONTHLY RENT", "currency", "required", "premises"),
    field("eviction_grounds", "Grounds for termination / eviction (e.g. Expiry of lease, Non-payment of rent, Personal bona fide need)", "EVICTION GROUNDS", "textarea", "required", "premises"),
    field("effective_date", "Date of notice", "DATE OF NOTICE", "date", "required", "demand"),
    field("vacate_deadline", "Deadline date to vacate and deliver possession", "VACATE DEADLINE", "date", "required", "demand"),
  ],
  clauses: [
    { id: "header", title: "NOTICE TO QUIT UNDER SECTION 106 OF TRANSFER OF PROPERTY ACT, 1882", required: true },
    { id: "tenancy_facts", title: "1. Tenancy Particulars and Description of Premises", required: true },
    { id: "termination_ground", title: "2. Grounds of Termination and Arrears", required: true },
    { id: "vacant_demand", title: "3. Demand for Peaceful Vacant Possession", required: true },
    { id: "legal_consequences", title: "4. Consequences of Default: Eviction Suit and Mesne Profits", required: true },
    { id: "signatures", title: "LANDLORD / ADVOCATE SIGNATURE", required: true, includeSignature: true },
  ],
};

export const NAME_CHANGE_AFFIDAVIT_TEMPLATE: TemplateSpec = {
  id: "name_change_affidavit",
  category: "affidavit",
  title: "Name Change Affidavit (அபெடவிட் / பெயர் மாற்ற உறுதிமொழி ஆவணம்)",
  description: "Formal affidavit on oath for change of name or correction of spelling in official records and Gazette publication.",
  documentType: "Affidavit for Change of Name",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Government of India Gazette & State Gazette Notification Guidelines",
    document_name: "Model Affidavit for Change of Name / Correction of Records",
    reference_date: "2026-01-01",
  },
  applicability: "Change of name after marriage, adoption, spelling correction, or personal preference.",
  executionRequirements: [
    "To be executed on non-judicial stamp paper of prescribed value (minimum ₹10/₹20/₹100 depending on state)",
    "Attested by Notary Public, Oath Commissioner, or Judicial Magistrate with official seal",
    "Followed by newspaper publication and Gazette notification",
  ],
  parties: [
    { id: "deponent", role: "Deponent", nameField: "new_name", typeField: "deponent_type", addressField: "deponent_address" },
  ],
  steps: [
    { id: "type", title: "Affidavit Type", description: "Change of name", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "Place of Swearing", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "names", title: "Old & New Name", description: "Previous name, new adopted name, parent/spouse name", fieldIds: ["old_name", "new_name", "parent_spouse_name", "deponent_address", "deponent_age"] },
    { id: "reason", title: "Reason for Change", description: "Marriage, personal choice, or spelling correction", fieldIds: ["change_reason", "effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("old_name", "Previous / Old name as per records", "OLD NAME", "text", "required", "names"),
    field("new_name", "New adopted name", "NEW NAME", "text", "required", "names"),
    field("parent_spouse_name", "Father's / Mother's / Husband's full name", "PARENT OR SPOUSE NAME", "text", "required", "names"),
    field("deponent_type", "Deponent category", "DEPONENT TYPE", "select", "required", "names", { options: PARTY_TYPE_OPTIONS }),
    field("deponent_address", "Permanent residential address", "RESIDENTIAL ADDRESS", "textarea", "required", "names"),
    field("deponent_age", "Age of deponent (years)", "AGE", "number", "required", "names", { min: 18, max: 120 }),
    field("change_reason", "Reason for name change (e.g. Post-marriage, Numerology, Correction)", "REASON FOR CHANGE", "textarea", "required", "reason"),
    field("effective_date", "Date of swearing affidavit", "DATE OF AFFIDAVIT", "date", "required", "reason"),
  ],
  clauses: [
    { id: "header", title: "BEFORE THE NOTARY PUBLIC / OATH COMMISSIONER", required: true },
    { id: "affirmation", title: "AFFIDAVIT FOR CHANGE OF NAME", required: true },
    { id: "declarations", title: "1. Declarations of Old Name and Identity", required: true },
    { id: "adoption_clause", title: "2. Renunciation of Old Name and Adoption of New Name", required: true },
    { id: "gazette_clause", title: "3. Use in Official Records and Gazette Publication", required: true },
    { id: "verification", title: "VERIFICATION ON OATH", required: true, includeSignature: true },
  ],
};

export const INDEMNITY_BOND_TEMPLATE: TemplateSpec = {
  id: "indemnity_bond",
  category: "affidavit",
  title: "Indemnity Bond",
  description: "Legal bond under Section 124 of Indian Contract Act, 1872 indemnifying a party against loss, missing certificates, or duplicate issuance.",
  documentType: "Indemnity Bond",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Section 124 of Indian Contract Act, 1872",
    document_name: "Model Indemnity Bond for Lost Documents / Claim Settlement",
    reference_date: "2026-01-01",
  },
  applicability: "Indemnifying banks, companies, universities, or authorities against loss for duplicate issuance.",
  executionRequirements: [
    "To be executed on non-judicial stamp paper of prescribed value",
    "May require notarization and surety attestation",
  ],
  parties: [
    { id: "indemnifier", role: "Indemnifier / Obligor", nameField: "indemnifier_name", typeField: "indemnifier_type", addressField: "indemnifier_address" },
    { id: "indemnified", role: "Indemnified / Obligee", nameField: "indemnified_name", typeField: "indemnified_type", addressField: "indemnified_address" },
  ],
  steps: [
    { id: "type", title: "Bond Type", description: "Indemnity Bond", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "parties", title: "Indemnifier & Indemnified", description: "Parties particulars", fieldIds: ["indemnifier_name", "indemnifier_type", "indemnifier_address", "indemnified_name", "indemnified_type", "indemnified_address"] },
    { id: "matter", title: "Circumstances & Loss", description: "Description of lost document or transaction", fieldIds: ["transaction_details", "indemnity_limit", "effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("indemnifier_name", "Indemnifier full name", "INDEMNIFIER NAME", "text", "required", "parties"),
    field("indemnifier_type", "Indemnifier type", "INDEMNIFIER TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("indemnifier_address", "Indemnifier permanent address", "INDEMNIFIER ADDRESS", "textarea", "required", "parties"),
    field("indemnified_name", "Indemnified company / authority / person name", "INDEMNIFIED NAME", "text", "required", "parties"),
    field("indemnified_type", "Indemnified type", "INDEMNIFIED TYPE", "select", "required", "parties", { options: PARTY_TYPE_OPTIONS }),
    field("indemnified_address", "Indemnified address", "INDEMNIFIED ADDRESS", "textarea", "required", "parties"),
    field("transaction_details", "Circumstances and description of instrument / claim", "TRANSACTION DETAILS", "textarea", "required", "matter"),
    field("indemnity_limit", "Maximum indemnified amount (₹ INR)", "INDEMNITY AMOUNT", "currency", "recommended", "matter"),
    field("effective_date", "Date of bond execution", "DATE OF BOND", "date", "required", "matter"),
  ],
  clauses: [
    { id: "title", title: "INDEMNITY BOND", required: true },
    { id: "recitals", title: "Recitals of Circumstances and Request", required: true },
    { id: "indemnity_obligation", title: "1. Covenant of Complete Indemnification and Hold Harmless", required: true },
    { id: "reimbursement", title: "2. Reimbursement of Losses, Costs and Legal Expenses", required: true },
    { id: "governing_law", title: "3. Governing Law and Jurisdiction", required: true, needsLegalContext: true },
    { id: "signatures", title: "IN WITNESS WHEREOF", required: true, includeSignature: true },
  ],
};

export const FOUNDER_AGREEMENT_TEMPLATE: TemplateSpec = {
  id: "founder_agreement",
  category: "agreement",
  title: "Co-Founders Agreement",
  description: "Startup co-founders agreement covering equity shareholding, 4-year vesting with 1-year cliff, IP assignment, and departure terms.",
  documentType: "Co-Founders Agreement",
  jurisdictionCountry: "IN",
  version: "2026.1",
  source: {
    authority: "Startup India Model Contracts & Companies Act, 2013",
    document_name: "Model Founders' Agreement for Indian Startups",
    reference_date: "2026-01-01",
  },
  applicability: "Early-stage startup co-founders incorporating an Indian entity.",
  executionRequirements: [
    "Executed on appropriate non-judicial stamp paper",
    "All founders to sign each page",
  ],
  parties: [
    { id: "founder_1", role: "Founder 1", nameField: "founder_1_name", typeField: "founder_1_type", addressField: "founder_1_address" },
    { id: "founder_2", role: "Founder 2", nameField: "founder_2_name", typeField: "founder_2_type", addressField: "founder_2_address" },
  ],
  steps: [
    { id: "type", title: "Founders Agreement", description: "Startup Co-founders Contract", fieldIds: ["document_title"] },
    { id: "jurisdiction", title: "Jurisdiction", description: "State & Seat", fieldIds: ["jurisdiction_country", "jurisdiction_region", "governing_law_seat"] },
    { id: "founders", title: "Founders Particulars", description: "Names, addresses", fieldIds: ["founder_1_name", "founder_1_type", "founder_1_address", "founder_2_name", "founder_2_type", "founder_2_address"] },
    { id: "venture", title: "Venture & Roles", description: "Company name, business domain", fieldIds: ["venture_name", "business_description", "founder_1_role", "founder_2_role"] },
    { id: "equity", title: "Equity & Vesting", description: "Equity split %, vesting schedule", fieldIds: ["founder_1_equity_percent", "founder_2_equity_percent", "effective_date"] },
  ],
  fields: [
    field("document_title", "Document title", "DOCUMENT TITLE", "text", "optional", "type"),
    ...jurisdictionFields(),
    field("venture_name", "Startup / Venture Name (or proposed name)", "VENTURE NAME", "text", "required", "venture"),
    field("business_description", "Nature of business / product concept", "BUSINESS DESCRIPTION", "textarea", "required", "venture"),
    field("founder_1_name", "Founder 1 full name", "FOUNDER 1 NAME", "text", "required", "founders"),
    field("founder_1_type", "Founder 1 type", "FOUNDER 1 TYPE", "select", "required", "founders", { options: PARTY_TYPE_OPTIONS }),
    field("founder_1_address", "Founder 1 permanent address", "FOUNDER 1 ADDRESS", "textarea", "required", "founders"),
    field("founder_1_role", "Founder 1 designated role (e.g. CEO)", "FOUNDER 1 ROLE", "text", "required", "venture"),
    field("founder_1_equity_percent", "Founder 1 equity ownership (%)", "FOUNDER 1 EQUITY", "number", "required", "equity"),
    field("founder_2_name", "Founder 2 full name", "FOUNDER 2 NAME", "text", "required", "founders"),
    field("founder_2_type", "Founder 2 type", "FOUNDER 2 TYPE", "select", "required", "founders", { options: PARTY_TYPE_OPTIONS }),
    field("founder_2_address", "Founder 2 permanent address", "FOUNDER 2 ADDRESS", "textarea", "required", "founders"),
    field("founder_2_role", "Founder 2 designated role (e.g. CTO)", "FOUNDER 2 ROLE", "text", "required", "venture"),
    field("founder_2_equity_percent", "Founder 2 equity ownership (%)", "FOUNDER 2 EQUITY", "number", "required", "equity"),
    field("effective_date", "Date of agreement execution", "AGREEMENT DATE", "date", "required", "equity"),
  ],
  clauses: [
    { id: "title", title: "CO-FOUNDERS AGREEMENT", required: true },
    { id: "venture_roles", title: "1. The Venture and Executive Responsibilities", required: true },
    { id: "equity_split", title: "2. Initial Equity Ownership", required: true },
    { id: "vesting_schedule", title: "3. 4-Year Vesting Schedule with 1-Year Cliff", required: true },
    { id: "ip_assignment", title: "4. Full Assignment of Intellectual Property to Company", required: true },
    { id: "non_compete", title: "5. Non-Compete and Non-Solicitation", required: true },
    { id: "departure_buyback", title: "6. Founder Departure and Equity Repurchase Rights", required: true },
    { id: "dispute_resolution", title: "7. Governing Law and Arbitration", required: true, needsLegalContext: true },
    { id: "signatures", title: "IN WITNESS WHEREOF", required: true, includeSignature: true },
  ],
};

export const MODEL_TEMPLATES: Record<string, TemplateSpec> = {
  [RENTAL_AGREEMENT_TAMIL_NADU_TEMPLATE.id]: RENTAL_AGREEMENT_TAMIL_NADU_TEMPLATE,
  [SALE_DEED_TEMPLATE.id]: SALE_DEED_TEMPLATE,
  [GENERAL_POWER_OF_ATTORNEY_TEMPLATE.id]: GENERAL_POWER_OF_ATTORNEY_TEMPLATE,
  [SPECIAL_POWER_OF_ATTORNEY_TEMPLATE.id]: SPECIAL_POWER_OF_ATTORNEY_TEMPLATE,
  [GIFT_DEED_TEMPLATE.id]: GIFT_DEED_TEMPLATE,
  [RELEASE_DEED_TEMPLATE.id]: RELEASE_DEED_TEMPLATE,
  [COMMERCIAL_LEASE_TEMPLATE.id]: COMMERCIAL_LEASE_TEMPLATE,
  [LEAVE_LICENSE_TEMPLATE.id]: LEAVE_LICENSE_TEMPLATE,
  [LOAN_AGREEMENT_TEMPLATE.id]: LOAN_AGREEMENT_TEMPLATE,
  [RTI_APPLICATION_TEMPLATE.id]: RTI_APPLICATION_TEMPLATE,
  [LEGAL_AID_APPLICATION_TEMPLATE.id]: LEGAL_AID_APPLICATION_TEMPLATE,
  [PAYMENT_DEMAND_NOTICE_TEMPLATE.id]: PAYMENT_DEMAND_NOTICE_TEMPLATE,
  [EVICTION_NOTICE_TEMPLATE.id]: EVICTION_NOTICE_TEMPLATE,
  [NAME_CHANGE_AFFIDAVIT_TEMPLATE.id]: NAME_CHANGE_AFFIDAVIT_TEMPLATE,
  [INDEMNITY_BOND_TEMPLATE.id]: INDEMNITY_BOND_TEMPLATE,
  [FOUNDER_AGREEMENT_TEMPLATE.id]: FOUNDER_AGREEMENT_TEMPLATE,
};
