"""Assemble a structured draft from a template and user values.

The assembler never invents party names, dates, amounts, or legal authorities.
Missing values become explicit placeholders.
"""

from __future__ import annotations

import re
from typing import Any, Mapping

from .types import TemplateSpec
from .validation import active_clauses, placeholder_for

TOKEN_RE = re.compile(r"\{([a-z0-9_]+)\}")
DISCLAIMER = (
    "This document is an AI-assisted draft generated by ChatLaw. It is not legal advice, "
    "is not a substitute for a lawyer, and is not valid merely because it was generated. "
    "Laws vary by jurisdiction. Review the draft, complete any placeholders, and obtain "
    "professional legal review before use."
)


def _value_text(template: TemplateSpec, values: Mapping[str, Any], field_id: str) -> str:
    fields = {field["id"]: field for field in template["fields"]}
    field = fields.get(field_id)
    raw = values.get(field_id)
    if field and field["type"] == "checkbox":
        return "yes" if raw in (True, "true", "yes", "on") else "no"
    if field and field["type"] == "select" and field.get("options") and raw not in (None, ""):
        for option in field["options"]:
            if option["value"] == str(raw):
                return option["label"]
    if raw is None:
        return placeholder_for(field) if field else f"[{field_id.replace('_', ' ').upper()} REQUIRED]"
    if isinstance(raw, str):
        text = raw.strip()
        if text:
            return text
        return placeholder_for(field) if field else f"[{field_id.replace('_', ' ').upper()} REQUIRED]"
    if isinstance(raw, bool):
        return "yes" if raw else "no"
    return str(raw)


def fill_body(template: TemplateSpec, values: Mapping[str, Any], body: str) -> str:
    fields = {field["id"]: field for field in template["fields"]}

    def replace(match: re.Match[str]) -> str:
        field_id = match.group(1)
        if field_id == "document_title":
            supplied = values.get("document_title")
            if isinstance(supplied, str) and supplied.strip():
                return supplied.strip()
            return template["document_type"]
        if field_id in fields or field_id in values:
            return _value_text(template, values, field_id)
        return f"[{field_id.replace('_', ' ').upper()} REQUIRED]"

    filled = TOKEN_RE.sub(replace, body)
    filled = re.sub(r" +", " ", filled)
    return filled.strip()


def signature_blocks(template: TemplateSpec, values: Mapping[str, Any]) -> list[dict[str, str]]:
    blocks = []
    for party in template["parties"]:
        blocks.append({
            "party_id": party["id"],
            "role": party["role"],
            "name": _value_text(template, values, party["name_field"]),
            "lines": [
                f"{party['role'].upper()}",
                f"Name: {_value_text(template, values, party['name_field'])}",
                "Signature: ______________________________",
                "Date: ______________________________",
            ],
        })
    return blocks


def resolve_provision_class(clause: Mapping[str, Any]) -> str:
    explicit = clause.get("provision_class")
    if explicit in {"required", "recommended", "user_specific"}:
        return explicit
    if clause.get("required"):
        return "required"
    if clause.get("condition"):
        return "recommended"
    return "user_specific"


def assemble_document(template: TemplateSpec, values: Mapping[str, Any]) -> dict[str, Any]:
    clauses = active_clauses(template, values)
    sections = []
    number = 1
    for clause in clauses:
        body = fill_body(template, values, clause["body"])
        section = {
            "id": clause["id"],
            "title": clause["title"],
            "body": body,
            "required": bool(clause.get("required")),
            "provision_class": resolve_provision_class(clause),
            "needs_legal_context": bool(clause.get("needs_legal_context")),
            "review_required": bool(clause.get("needs_legal_context")),
            "citation_ids": [],
            "legal_basis": [],
            "include_signature": bool(clause.get("include_signature")),
            "number": None if clause["id"] in {"title", "signatures"} else number,
        }
        if section["number"] is not None:
            number += 1
        sections.append(section)
    title = _value_text(template, values, "document_title")
    if title.startswith("["):
        title = template["document_type"]
    warnings = [
        {"code": "ai_generated", "message": DISCLAIMER},
        {"code": "jurisdiction_retained",
         "message": f"Jurisdiction recorded as India — {values.get('jurisdiction_region') or '[STATE OR UNION TERRITORY REQUIRED]'}."},
    ]
    if any(section["needs_legal_context"] for section in sections):
        warnings.append({
            "code": "jurisdiction_review",
            "message": "Jurisdiction-specific clauses are marked for review until verified legal sources are attached.",
        })
    return {
        "template_id": template["id"],
        "title": title,
        "document_type": template["document_type"],
        "jurisdiction_country": values.get("jurisdiction_country") or "IN",
        "jurisdiction_region": values.get("jurisdiction_region") or "",
        "sections": sections,
        "signatures": signature_blocks(template, values),
        "warnings": warnings,
        "citations": [],
        "model_used": False,
    }
